# === Buka Aplikasi Android ===
#map Alt+w app.launch com.whatsapp
#map Alt+t app.launch org.telegram.messenger
#map Alt+y app.launch "YouTube"
map Alt+v app.launch via
#map Alt+b app.launch "Firefox Nightly"

# === Navigasi Window & Pane ===
map Alt+r window.rename_prompt
map Alt+g pane.equalize
map Alt+e pane.equalize

# === Bikin & Atur Layout ===
map Alt+1 pane.layout grid
map Alt+2 pane.move_to_edge left
map Alt+w window.select 0

# === Kirim Perintah Otomatis ke Terminal ===
map Alt+c send-key ctrl+c
map Alt+h send-text "echo Halo dari shortcut!\n"

# === Hapus Shortcut Bawaan (kalau mau) ===
# unmap alt+u
