set -as terminal-features ',*:sixel'

set -g allow-passthrough on

set -ag terminal-overrides ',*:passthrough=on'

set -as terminal-features ',*:extkeys'

# Disable the status bar entirely
set -g status off
set -g focus-events on
set -g history-limit 50000
# If keeping the status bar, update it as rarely as possible (e.g., every 24 hours)
set -g status-interval 0
set -sg escape-time 0
# Disable automatic window renaming
setw -g automatic-rename off

# Turn off administrative cell activity monitoring
setw -g monitor-activity off
set -g visual-activity off


# Hide inactive pane borders
# Hide borders by blending them into a dark terminal background
set -g pane-border-style fg=#000000,bg=default
set -g pane-active-border-style fg=#000000,bg=default
set -g pane-border-lines single
set -g pane-border-format ""

set -g pane-border-status off
set -g default-terminal "tmux-256color"
set -g default-terminal "screen-256color"
set -as terminal-overrides ',xterm-256color:Tc'

set -g status "off"
set -g status-style bg=default,fg=#cdd6f4

# keybinding
unbind C-b

unbind %
bind -n M-T split-window -h
unbind '"'
bind -n M-t split-window -v
bind -n M-c new-window
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R
bind -n M-q kill-pane
# Use Vim-style pane resizing
bind -n M-H resize-pane -L 5
bind -n M-J resize-pane -D 5
bind -n M-K resize-pane -U 5
bind -n M-L resize-pane -R 5

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

bind -n M-Q detach-client
